services:
  - type: web
    name: shortly-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shortly-db
          property: connectionString
